import { expect, test } from '@playwright/test';

test.describe.configure({ mode: 'serial' });

test('develop, inspect, correct and preserve a research direction', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: '新建研究课题', exact: true }).click();
  await page.getByLabel('课题名称').fill('长视频中的信息保留');
  await page.getByLabel('希望探索的问题').fill('视频压缩如何保留未知问题需要的信息？');
  await page.getByRole('button', { name: '建立课题' }).click();
  await page.getByRole('button', { name: '导入论文片段' }).click();
  await page.getByLabel('资料标题').fill('A supplied research passage');
  await page.getByLabel('原文或笔记').fill('A synthetic test passage describing task-conditioned selection before a language model.');
  await page.getByRole('dialog').getByRole('button', { name: '导入材料', exact: true }).click();
  await page.getByRole('button', { name: '开始探索', exact: true }).click();
  await expect(page.getByRole('heading', { name: '任务条件下的信息保留', level: 2, exact: true })).toBeVisible();
  await page.getByRole('button', { name: '保留方向', exact: true }).click();
  await expect(page.getByRole('button', { name: '已保留', exact: true })).toBeVisible();
  await page.getByRole('tab', { name: '方法结构', exact: true }).click();
  await expect(page.getByRole('group', { name: '方法机制图' })).toBeVisible();
  await page.getByRole('button', { name: '处理对象 视频表征' }).click();
  await expect(page.locator('.node-detail')).toContainText('视频表征');
  await page.screenshot({ path: 'test-results/mechanism-desktop.png', fullPage: true });
  await page.getByLabel('研究反馈').fill('应考虑选择时无法获得未来问题的情况，进一步研究信息价值。');
  await page.getByRole('button', { name: '提交反馈' }).click();
  await expect(page.locator('.pending')).toBeVisible();
  await page.getByRole('tab', { name: '经验', exact: true }).click();
  await page.getByRole('button', { name: '记录经验', exact: true }).click();
  await page.getByLabel('经验或判断').fill('选择规则需要区分问题已知与未知的条件');
  await page.getByLabel('适用条件').fill('压缩发生在用户提问之前');
  await page.getByRole('button', { name: '保存经验', exact: true }).click();
  await expect(page.locator('.memory')).toContainText('压缩发生在用户提问之前');
  await page.getByRole('tab', { name: '历史', exact: true }).click();
  const revision = (await page.locator('.project-header .eyebrow').innerText()).match(/V(\d+)/)?.[1];
  expect(revision).toBeTruthy();
  await expect(page.locator('.research-content details').first()).toContainText(`版本 ${revision}`);
  const downloadReady = page.waitForEvent('download');
  await page.getByRole('link', { name: '导出研究快照' }).click();
  expect((await downloadReady).suggestedFilename()).toBe('research-snapshot.json');
  await page.getByRole('tab', { name: '经验', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/workbench-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

test('save model configuration without restarting and never refill the key', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: '运行设置' }).click();
  await expect(page.getByLabel('模型名', {exact: true})).toHaveValue('fixture');
  await expect(page.getByRole('dialog').locator('input')).toHaveCount(3);
  await expect(page.getByRole('dialog').locator('select')).toHaveCount(0);
  await page.getByLabel('模型名', {exact: true}).fill('browser-test-model');
  await page.getByLabel('API Key', {exact: true}).fill('browser-test-secret');
  await page.getByRole('button', { name: '保存模型配置' }).click();
  await expect(page.getByRole('status')).toContainText('已保存');
  await expect(page.getByLabel('API Key', {exact: true})).toHaveValue('');
  await page.reload();
  await page.getByRole('button', { name: '运行设置' }).click();
  await expect(page.getByLabel('模型名', {exact: true})).toHaveValue('browser-test-model');
  await expect(page.getByLabel('API Key', {exact: true})).toHaveValue('');
  await page.getByRole('button', { name: '保存模型配置' }).click();
  await expect(page.getByRole('status')).toContainText('已保存');
  await page.screenshot({path: 'test-results/live-settings.png', fullPage: true});
});

test('assign and remove a second model while preserving the default model', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', {name: '运行设置'}).click();
  await page.getByRole('button', {name: '添加模型'}).click();
  const second = page.getByRole('region', {name: '模型 2', exact: true});
  await second.getByLabel('API URL', {exact: true}).fill('https://critic.test/v1');
  await second.getByLabel('API Key', {exact: true}).fill('critic-browser-test-key');
  await second.getByLabel('模型名', {exact: true}).fill('critic-model');
  await page.getByLabel('文献分析', {exact: true}).selectOption({label: '模型 2 · critic-model'});
  await page.getByLabel('方案审查', {exact: true}).selectOption({label: '模型 2 · critic-model'});
  await page.getByRole('button', {name: '保存模型配置'}).click();
  await expect(page.getByRole('status')).toContainText('已保存');
  await page.reload();
  await page.getByRole('button', {name: '运行设置'}).click();
  await expect(second.getByLabel('模型名', {exact: true})).toHaveValue('critic-model');
  await expect(second.getByLabel('API Key', {exact: true})).toHaveValue('');
  await expect(page.getByLabel('方案审查').locator('option:checked')).toHaveText('模型 2 · critic-model');
  await page.screenshot({path: 'test-results/multi-model-settings.png', fullPage: true});
  await second.getByRole('button', {name: '移除'}).click();
  await page.getByRole('button', {name: '保存模型配置'}).click();
  await expect(page.getByRole('status')).toContainText('已保存');
  await page.reload();
  await page.getByRole('button', {name: '运行设置'}).click();
  await expect(page.getByRole('dialog').locator('input')).toHaveCount(3);
  await expect(page.getByLabel('模型名', {exact: true})).toHaveValue('browser-test-model');
});
