import { expect, test } from '@playwright/test';

test('develop, inspect, correct and preserve a research direction', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: '新建研究课题', exact: true }).click();
  await page.getByLabel('课题名称').fill('长视频中的信息保留');
  await page.getByLabel('希望探索的问题').fill('视频压缩如何保留未知问题需要的信息？');
  await page.getByRole('button', { name: '建立课题' }).click();
  await page.getByRole('button', { name: '导入论文片段' }).click();
  await page.getByLabel('资料标题').fill('A supplied research passage');
  await page.getByLabel('原文或笔记').fill('A synthetic test passage describing task-conditioned selection before a language model.');
  await page.getByRole('dialog').getByRole('button', { name: '导入材料', exact: true }).click();
  await page.getByRole('button', { name: '开始探索', exact: true }).click();
  await expect(page.getByRole('heading', { name: '任务条件下的信息保留', level: 2, exact: true })).toBeVisible();
  await page.getByRole('button', { name: '保留方向', exact: true }).click();
  await expect(page.getByRole('button', { name: '已保留', exact: true })).toBeVisible();
  await page.getByRole('tab', { name: '方法结构', exact: true }).click();
  await expect(page.getByRole('group', { name: '方法机制图' })).toBeVisible();
  await page.getByRole('button', { name: '处理对象 视频表征' }).click();
  await expect(page.locator('.node-detail')).toContainText('视频表征');
  await page.screenshot({ path: 'test-results/mechanism-desktop.png', fullPage: true });
  await page.getByLabel('研究反馈').fill('应考虑选择时无法获得未来问题的情况，进一步研究信息价值。');
  await page.getByRole('button', { name: '提交反馈' }).click();
  await expect(page.locator('.pending')).toBeVisible();
  await page.getByRole('tab', { name: '经验', exact: true }).click();
  await page.getByRole('button', { name: '记录经验', exact: true }).click();
  await page.getByLabel('经验或判断').fill('选择规则需要区分问题已知与未知的条件');
  await page.getByLabel('适用条件').fill('压缩发生在用户提问之前');
  await page.getByRole('button', { name: '保存经验', exact: true }).click();
  await expect(page.locator('.memory')).toContainText('压缩发生在用户提问之前');
  await page.getByRole('tab', { name: '历史', exact: true }).click();
  const revision = (await page.locator('.project-header .eyebrow').innerText()).match(/V(\d+)/)?.[1];
  expect(revision).toBeTruthy();
  await expect(page.locator('.research-content details').first()).toContainText(`版本 ${revision}`);
  const downloadReady = page.waitForEvent('download');
  await page.getByRole('link', { name: '导出研究快照' }).click();
  expect((await downloadReady).suggestedFilename()).toBe('research-snapshot.json');
  await page.getByRole('tab', { name: '经验', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/workbench-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
